version: "3"

services:
  with-docker-multi-env-development:
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
      args:
        - env=development
    image: with-docker-multi-env-development
    ports:
      - "3001:3000"